/*T?O PDB*/
ALTER SYSTEM SET db_create_file_dest = 'C:\PHAMMEM\oradata\ORCL';
CREATE PLUGGABLE DATABASE pdbchungkhoan ADMIN USER chungkhoan_ad IDENTIFIED BY 1201;
ALTER PLUGGABLE DATABASE pdbchungkhoan OPEN;
ALTER PLUGGABLE DATABASE pdbchungkhoan SAVE STATE;
/*show pdbs;
show con_name;
select *from all_users*/

/*KI?M TRA TABLESPACE*/
SELECT tablespace_name, con_id FROM cdb_tablespaces;

/*T?O TABLESPACE CHO PDBCHUNGKHOAN*/
ALTER SESSION SET CONTAINER = PDBCHUNGKHOAN;
alter session set "_ORACLE_SCRIPT"=true;

-- t?o tabespace
CREATE TABLESPACE CHUNGKHOAN DATAFILE 
'C:/PHAMMEM/oradata/ORCL/CHUNGKHOANPDB/CHUNGKHOAN_PROJECT.dbf' SIZE 1G AUTOEXTEND ON NEXT 1G MAXSIZE 8G;
ALTER TABLESPACE CHUNGKHOAN add datafile 'C:/PHAMMEM/oradata/ORCL/CHUNGKHOANPDB/CHUNGKHOAN_PROJECT_1.dbf' size 8G;



ALTER SESSION SET CONTAINER=CDB$ROOT; --CDB$ROOT
SELECT tablespace_name, con_id FROM CDB_TABLESPACES;

CREATE USER user1_ck IDENTIFIED BY 1201;
GRANT CONNECT TO user1_ck;
GRANT CREATE SESSION, GRANT ANY PRIVILEGE TO user1_ck;
GRANT UNLIMITED TABLESPACE TO user1_ck;
-- Basic permission
GRANT CREATE  TABLE to user1_ck;
GRANT CREATE  TRIGGER to user1_ck;
GRANT CREATE  SEQUENCE to user1_ck;
GRANT CREATE  PROCEDURE to user1_ck;
GRANT CREATE VIEW TO user1_ck;